import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'

import {
  BASELINE_MIGRATION,
  BASELINE_VERSION,
  assembleBaseline,
  verifiedFragmentPaths,
} from '../migration-replay/assemble-baseline.mjs'
import {
  forwardMigrations,
  prepareBaselineWorkspace,
} from '../migration-replay/baseline-workspace.mjs'

const root = process.cwd()
const temporaryRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'noven-materialized-baseline-'))
const assembledPath = path.join(temporaryRoot, 'assembled.sql')

try {
  const verified = verifiedFragmentPaths()
  assert.equal(verified.entries.length, 39)
  assert.equal(verified.manifest.inventory.tables, 31)
  assert.equal(verified.manifest.inventory.columns, 384)
  assert.equal(verified.manifest.inventory.constraints, 226)
  assert.equal(verified.manifest.inventory.functions, 112)
  assert.equal(verified.manifest.inventory.views, 12)

  const assembled = assembleBaseline({ outputPath: assembledPath })
  const sql = fs.readFileSync(assembledPath, 'utf8')
  const count = (pattern) => sql.match(pattern)?.length ?? 0

  assert.equal(assembled.fragmentCount, 39)
  assert.equal(count(/^CREATE TABLE /gm), 31)
  assert.equal(count(/^ALTER TABLE ONLY .* ADD CONSTRAINT /gm), 226)
  assert.equal(count(/^CREATE (?:UNIQUE )?INDEX /gm), 128)
  assert.equal(count(/^CREATE OR REPLACE FUNCTION /gm), 112)
  assert.equal(count(/^CREATE OR REPLACE VIEW /gm), 12)
  assert.equal(count(/WITH \(security_invoker=true\)/g), 12)
  assert.equal(count(/^CREATE (?:CONSTRAINT )?TRIGGER /gm), 29)
  assert.equal(count(/^CREATE POLICY /gm), 17)
  assert.equal(count(/ GENERATED BY DEFAULT AS IDENTITY/g), 6)
  assert.equal(count(/^CREATE SEQUENCE /gm), 0)

  assert.doesNotMatch(sql, /desafio5s_archive/)
  assert.doesNotMatch(sql, /dedup_turrocklets_backup_20260805/)
  assert.doesNotMatch(sql, /productos_descripcion_backup_20260805/)
  assert.doesNotMatch(sql, /productos_familia_backup_20260806/)
  assert.doesNotMatch(sql, /gerente091@gmail\.com/)
  assert.doesNotMatch(sql, /3449476/)

  assert.throws(
    () =>
      prepareBaselineWorkspace({
        repositoryRoot: root,
        workspaceRoot: path.join(temporaryRoot, 'without-guard'),
        env: {},
      }),
    /explicitly disposable environment/,
  )

  const workspace = path.join(temporaryRoot, 'workspace')
  const prepared = prepareBaselineWorkspace({
    repositoryRoot: root,
    workspaceRoot: workspace,
    env: { NOVEN_EPHEMERAL_REPLAY: '1' },
  })
  const migrationFiles = fs
    .readdirSync(prepared.migrationsDir)
    .filter((name) => name.endsWith('.sql'))
    .sort()
  const expectedForward = forwardMigrations({ repositoryRoot: root }).map(
    ({ filename }) => filename,
  )

  assert.deepEqual(migrationFiles, [BASELINE_MIGRATION, ...expectedForward].sort())
  for (const filename of expectedForward) {
    const version = /^\d+/.exec(filename)?.[0]
    assert.ok(version)
    assert.ok(BigInt(version) > BigInt(BASELINE_VERSION))
  }

  const replayManifest = JSON.parse(
    fs.readFileSync(path.join(workspace, 'baseline-replay-manifest.json'), 'utf8'),
  )
  assert.equal(replayManifest.historical_migrations_copied, false)
  assert.equal(replayManifest.production_ledger_action, 'none')
  assert.deepEqual(replayManifest.forward_migrations, expectedForward)

  assert.throws(
    () =>
      prepareBaselineWorkspace({
        repositoryRoot: root,
        workspaceRoot: workspace,
        env: { NOVEN_EPHEMERAL_REPLAY: '1' },
      }),
    /non-empty disposable migrations directory/,
  )

  console.log('migration replay materialized baseline: OK')
} finally {
  fs.rmSync(temporaryRoot, { recursive: true, force: true })
}
