CREATE SCHEMA IF NOT EXISTS noven_private;

CREATE EXTENSION IF NOT EXISTS pgcrypto
WITH SCHEMA extensions;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
WITH SCHEMA extensions;

CREATE EXTENSION IF NOT EXISTS pg_net
WITH SCHEMA public;

CREATE EXTENSION IF NOT EXISTS supabase_vault
WITH SCHEMA vault;
