CREATE TABLE public.acciones_operativas (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  tipo text NOT NULL,
  cantidad integer NOT NULL,
  producto_id uuid NOT NULL,
  vencimiento_id uuid,
  sucursal_id uuid NOT NULL,
  usuario_id uuid NOT NULL,
  fecha timestamp with time zone DEFAULT now() NOT NULL,
  trimestre integer NOT NULL,
  anio integer NOT NULL,
  observaciones text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  costo_unitario_sin_iva numeric,
  costo_observado_at timestamp with time zone,
  valorizacion_metodo text
);

CREATE TABLE public.alertas_zonales (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organizacion_id uuid NOT NULL,
  zona_id uuid NOT NULL,
  producto_id uuid NOT NULL,
  familia_id uuid NOT NULL,
  sucursal_origen_id uuid NOT NULL,
  vencimiento_origen_id uuid NOT NULL,
  fecha_vencimiento date NOT NULL,
  nivel_origen text NOT NULL,
  estado text DEFAULT 'activa'::text NOT NULL,
  first_detected_at timestamp with time zone DEFAULT now() NOT NULL,
  last_detected_at timestamp with time zone DEFAULT now() NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.alertas_zonales_destinos (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  alerta_id uuid NOT NULL,
  organizacion_id uuid NOT NULL,
  zona_id uuid NOT NULL,
  sucursal_id uuid NOT NULL,
  usuario_id uuid,
  stock_snapshot integer NOT NULL,
  stock_actualizado_at timestamp with time zone,
  estado text NOT NULL,
  notificada_at timestamp with time zone,
  respuesta_at timestamp with time zone,
  cantidad_confirmada integer,
  fecha_confirmada date,
  vencimiento_destino_id uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.familias (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  codigo text NOT NULL,
  nombre text NOT NULL,
  sector_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  organizacion_id uuid NOT NULL
);

CREATE TABLE public.importacion_0258_detalle (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  importacion_id uuid NOT NULL,
  organizacion_id uuid NOT NULL,
  sucursal_id uuid NOT NULL,
  producto_id uuid,
  cod_art text NOT NULL,
  descripcion text,
  marca text,
  contenido text,
  unidad_medida text,
  bulto numeric,
  dto_sec_fam text,
  costo_unitario numeric,
  costo_final numeric,
  precio_sugerido numeric,
  precio_venta numeric,
  stock_transito numeric,
  stock numeric,
  per_ant_3 numeric,
  per_ant_2 numeric,
  per_ant_1 numeric,
  ultimo_periodo numeric,
  venta_media_diaria numeric,
  fila_origen integer,
  captured_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.importaciones (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organizacion_id uuid NOT NULL,
  sucursal_id uuid NOT NULL,
  usuario_id uuid,
  tipo_reporte text NOT NULL,
  codigo_sucursal_fuente text NOT NULL,
  fecha_reporte date,
  nombre_archivo text NOT NULL,
  archivo_sha256 text NOT NULL,
  filas_total integer DEFAULT 0 NOT NULL,
  filas_validas integer DEFAULT 0 NOT NULL,
  filas_descartadas integer DEFAULT 0 NOT NULL,
  estado text DEFAULT 'recibida'::text NOT NULL,
  error_detalle text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  aplicada_at timestamp with time zone,
  modo text DEFAULT 'familia'::text NOT NULL,
  filas_aplicadas integer DEFAULT 0 NOT NULL,
  filas_sin_mapear integer DEFAULT 0 NOT NULL,
  filas_sin_familia integer DEFAULT 0 NOT NULL
);

CREATE TABLE public.intervenciones_rag (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organizacion_id uuid NOT NULL,
  sucursal_id uuid NOT NULL,
  producto_id uuid NOT NULL,
  vencimiento_id uuid NOT NULL,
  usuario_id uuid NOT NULL,
  porcentaje_descuento numeric(5,2) NOT NULL,
  cantidad_comprometida_al_aplicar numeric NOT NULL,
  vmd_glaciar_al_aplicar numeric,
  aplicado_at timestamp with time zone DEFAULT now() NOT NULL,
  nota text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  finalizado_at timestamp with time zone,
  finalizado_por uuid,
  motivo_finalizacion text,
  nota_finalizacion text
);

CREATE TABLE public.invitaciones_acceso (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  usuario_id uuid,
  organizacion_id uuid NOT NULL,
  email text NOT NULL,
  nombre text NOT NULL,
  rol text NOT NULL,
  zona_id uuid,
  sucursal_id uuid,
  creado_por uuid NOT NULL,
  canal text NOT NULL,
  estado text DEFAULT 'pendiente'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  accepted_at timestamp with time zone,
  anulada_at timestamp with time zone,
  expires_at timestamp with time zone DEFAULT now() + '72:00:00'::interval NOT NULL,
  familias_ids uuid[] DEFAULT ARRAY[]::uuid[] NOT NULL,
  auth_deleted_at timestamp with time zone
);

CREATE TABLE public.organizaciones (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  codigo text NOT NULL,
  nombre text NOT NULL,
  activa boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.problemas_economicos_ciclos (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organizacion_id uuid NOT NULL,
  sucursal_id uuid NOT NULL,
  vencimiento_id uuid NOT NULL,
  producto_id uuid NOT NULL,
  abierto_at timestamp with time zone NOT NULL,
  abierto_por uuid,
  apertura_fuente text NOT NULL,
  apertura_metodo text NOT NULL,
  nivel_apertura text NOT NULL,
  cantidad_apertura numeric NOT NULL,
  unidades_expuestas_apertura numeric NOT NULL,
  costo_unitario_sin_iva_apertura numeric,
  dinero_en_riesgo_apertura numeric,
  ultimo_estado_at timestamp with time zone NOT NULL,
  ultimo_actor uuid,
  ultima_fuente text NOT NULL,
  nivel_actual text,
  cantidad_actual numeric NOT NULL,
  unidades_expuestas_actual numeric NOT NULL,
  costo_unitario_sin_iva_actual numeric,
  dinero_en_riesgo_actual numeric,
  resuelto_at timestamp with time zone,
  resuelto_por uuid,
  resolucion text,
  resolucion_fuente text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.producto_codigos (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organizacion_id uuid NOT NULL,
  producto_id uuid NOT NULL,
  codigo text NOT NULL,
  tipo text DEFAULT 'otro'::text NOT NULL,
  es_principal boolean DEFAULT false NOT NULL,
  activo boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.producto_costo_observaciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  organizacion_id uuid NOT NULL,
  producto_id uuid NOT NULL,
  sucursal_fuente_id uuid NOT NULL,
  importacion_id uuid NOT NULL,
  costo_unitario numeric,
  costo_final numeric,
  observado_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.producto_costo_ultima_observacion (
  producto_id uuid NOT NULL,
  organizacion_id uuid NOT NULL,
  sucursal_fuente_id uuid NOT NULL,
  importacion_id uuid NOT NULL,
  costo_unitario numeric,
  costo_final numeric,
  observado_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.producto_imagen_cambios (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  organizacion_id uuid NOT NULL,
  producto_id uuid NOT NULL,
  sucursal_id uuid NOT NULL,
  usuario_id uuid NOT NULL,
  accion text NOT NULL,
  imagen_url text NOT NULL,
  imagen_thumb_url text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.producto_pendiente_detecciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  pendiente_id uuid NOT NULL,
  organizacion_id uuid NOT NULL,
  sucursal_id uuid NOT NULL,
  importacion_id uuid NOT NULL,
  stock integer NOT NULL,
  venta_media_diaria numeric DEFAULT 0 NOT NULL,
  fila_origen integer,
  detected_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.producto_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  importacion_id uuid NOT NULL,
  organizacion_id uuid NOT NULL,
  sucursal_id uuid NOT NULL,
  producto_id uuid NOT NULL,
  stock integer NOT NULL,
  venta_media_diaria numeric DEFAULT 0 NOT NULL,
  fila_origen integer,
  captured_at timestamp with time zone DEFAULT now() NOT NULL,
  stock_transito numeric,
  per_ant_3 numeric,
  per_ant_2 numeric,
  per_ant_1 numeric,
  ultimo_periodo numeric,
  costo_unitario_observado numeric,
  costo_final_observado numeric,
  precio_sugerido numeric,
  precio_venta numeric
);

CREATE TABLE public.producto_sucursal (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organizacion_id uuid NOT NULL,
  producto_id uuid NOT NULL,
  sucursal_id uuid NOT NULL,
  stock_actual integer DEFAULT 0 NOT NULL,
  venta_media_diaria numeric DEFAULT 0 NOT NULL,
  fecha_ultima_importacion timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  stock_transito numeric,
  per_ant_3 numeric,
  per_ant_2 numeric,
  per_ant_1 numeric,
  ultimo_periodo numeric,
  precio_sugerido numeric,
  precio_venta numeric,
  fecha_ultima_importacion_0258 timestamp with time zone
);

CREATE TABLE public.productos (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  cod_art text NOT NULL,
  codigo_barras text,
  descripcion text NOT NULL,
  marca text,
  categoria text,
  proveedor text,
  sector text,
  venta_media_diaria numeric(10,2) DEFAULT 0 NOT NULL,
  stock_actual integer DEFAULT 0 NOT NULL,
  precio_costo numeric(10,2),
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  gramaje text,
  imagen_url text,
  familia_id uuid,
  organizacion_id uuid NOT NULL,
  imagen_thumb_url text
);

CREATE TABLE public.productos_pendientes_catalogo (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organizacion_id uuid NOT NULL,
  cod_art text NOT NULL,
  descripcion text NOT NULL,
  marca text,
  gramaje text,
  producto_id uuid,
  estado text DEFAULT 'pendiente'::text NOT NULL,
  familia_id_resuelta uuid,
  clasificado_por uuid,
  clasificado_at timestamp with time zone,
  first_detected_at timestamp with time zone DEFAULT now() NOT NULL,
  last_detected_at timestamp with time zone DEFAULT now() NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.push_subscriptions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  usuario_id uuid NOT NULL,
  subscription jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.rag_escalamientos (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organizacion_id uuid NOT NULL,
  sucursal_id uuid NOT NULL,
  producto_id uuid NOT NULL,
  vencimiento_id uuid NOT NULL,
  rag_id uuid NOT NULL,
  observacion_id bigint NOT NULL,
  estado_seguimiento text NOT NULL,
  rag_porcentaje numeric(5,2) NOT NULL,
  cantidad_actual numeric NOT NULL,
  unidades_expuestas numeric NOT NULL,
  velocidad_observada numeric,
  velocidad_necesaria numeric,
  costo_unitario_sin_iva numeric,
  dinero_en_riesgo_sin_iva numeric,
  detectado_at timestamp with time zone DEFAULT now() NOT NULL,
  push_solicitado_at timestamp with time zone,
  push_request_id bigint,
  push_procesado_at timestamp with time zone,
  push_destinatarios integer,
  push_enviados integer,
  respondido_at timestamp with time zone,
  respondido_por uuid,
  respuesta_tipo text,
  respuesta_referencia text
);

CREATE TABLE public.regiones (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organizacion_id uuid NOT NULL,
  codigo text NOT NULL,
  nombre text NOT NULL,
  activa boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.sectores (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  codigo text NOT NULL,
  nombre text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  organizacion_id uuid NOT NULL,
  dias_donacion integer
);

CREATE TABLE public.sucursales (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  nombre text NOT NULL,
  direccion text,
  activa boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  codigo text NOT NULL,
  organizacion_id uuid NOT NULL,
  zona_id uuid NOT NULL
);

CREATE TABLE public.usuario_accesos (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  usuario_id uuid NOT NULL,
  organizacion_id uuid NOT NULL,
  rol text NOT NULL,
  zona_id uuid,
  sucursal_id uuid,
  activo boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.usuario_familias (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  usuario_id uuid,
  familia_id uuid,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.usuario_familias_sucursal (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  usuario_id uuid NOT NULL,
  organizacion_id uuid NOT NULL,
  sucursal_id uuid NOT NULL,
  familia_id uuid NOT NULL,
  activo boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.usuarios (
  id uuid NOT NULL,
  nombre text NOT NULL,
  rol text DEFAULT 'operador'::text NOT NULL,
  sucursal_id uuid,
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.vencimiento_observaciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  organizacion_id uuid NOT NULL,
  sucursal_id uuid NOT NULL,
  producto_id uuid NOT NULL,
  vencimiento_id uuid NOT NULL,
  usuario_id uuid NOT NULL,
  cantidad_comprometida numeric NOT NULL,
  observada_at timestamp with time zone DEFAULT now() NOT NULL,
  nota text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.vencimientos (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  producto_id uuid NOT NULL,
  sucursal_id uuid NOT NULL,
  usuario_id uuid NOT NULL,
  cantidad integer NOT NULL,
  lote text,
  fecha_vencimiento date NOT NULL,
  fecha_carga timestamp with time zone DEFAULT now(),
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  nivel_actual text
);

CREATE TABLE public.zonas (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  organizacion_id uuid NOT NULL,
  codigo text NOT NULL,
  nombre text NOT NULL,
  activa boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  region_id uuid NOT NULL
);
