-- =============================================================================
-- NOVEN · PRODUCT IMAGE PIPELINE V2
--
-- Objetivo:
--   - una foto de catálogo por producto global, compartida por la organización;
--   - thumbnail separado para listas móviles;
--   - auditoría de alta/reemplazo;
--   - operadores pueden agregar una foto faltante;
--   - reemplazos requieren supervisor/gerencia;
--   - compatibilidad con URLs legacy hasta que cada SKU sea actualizado.
--
-- Esta migración es ADITIVA. El hardening del bucket se hace en 00320 una vez
-- que el frontend V2 esté desplegado.
-- =============================================================================

BEGIN;

ALTER TABLE public.productos
  ADD COLUMN IF NOT EXISTS imagen_thumb_url text;

GRANT SELECT (imagen_thumb_url) ON TABLE public.productos TO authenticated;

CREATE TABLE IF NOT EXISTS public.producto_imagen_cambios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizacion_id uuid NOT NULL REFERENCES public.organizaciones(id) ON DELETE CASCADE,
  producto_id uuid NOT NULL,
  sucursal_id uuid NOT NULL,
  usuario_id uuid NOT NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
  accion text NOT NULL CHECK (accion IN ('agregar', 'reemplazar')),
  imagen_url text NOT NULL,
  imagen_thumb_url text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT producto_imagen_cambios_producto_org_fk
    FOREIGN KEY (producto_id, organizacion_id)
    REFERENCES public.productos(id, organizacion_id)
    ON DELETE CASCADE,
  CONSTRAINT producto_imagen_cambios_sucursal_org_fk
    FOREIGN KEY (sucursal_id, organizacion_id)
    REFERENCES public.sucursales(id, organizacion_id)
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS producto_imagen_cambios_producto_fecha_idx
  ON public.producto_imagen_cambios(producto_id, created_at DESC);

CREATE INDEX IF NOT EXISTS producto_imagen_cambios_sucursal_fecha_idx
  ON public.producto_imagen_cambios(sucursal_id, created_at DESC);

ALTER TABLE public.producto_imagen_cambios ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.producto_imagen_cambios FROM PUBLIC, anon, authenticated;

DROP VIEW IF EXISTS public.v_vencimientos_operativos;

CREATE VIEW public.v_vencimientos_operativos
WITH (security_invoker = true)
AS
SELECT
  v.id,
  v.producto_id,
  v.sucursal_id,
  v.usuario_id,
  v.cantidad,
  v.lote,
  v.fecha_vencimiento,
  v.fecha_carga,
  v.activo,
  v.created_at,
  v.updated_at,
  v.nivel_actual,

  p.organizacion_id,
  p.cod_art,
  p.codigo_barras,
  p.descripcion,
  p.marca,
  p.gramaje,
  p.categoria,
  p.proveedor,
  p.sector,
  p.precio_costo,
  p.imagen_url,
  p.imagen_thumb_url,
  p.familia_id,
  p.activo AS producto_activo,
  p.created_at AS producto_created_at,
  p.updated_at AS producto_updated_at,

  f.sector_id,
  s.nombre AS sector_nombre,
  s.dias_donacion,

  ps.stock_actual,
  ps.venta_media_diaria,
  ps.fecha_ultima_importacion,
  ps.updated_at AS estado_updated_at
FROM public.vencimientos v
JOIN public.productos p
  ON p.id = v.producto_id
JOIN public.producto_sucursal ps
  ON ps.producto_id = v.producto_id
 AND ps.sucursal_id = v.sucursal_id
 AND ps.organizacion_id = p.organizacion_id
LEFT JOIN public.familias f
  ON f.id = p.familia_id
 AND f.organizacion_id = p.organizacion_id
LEFT JOIN public.sectores s
  ON s.id = f.sector_id
 AND s.organizacion_id = p.organizacion_id;

REVOKE ALL ON TABLE public.v_vencimientos_operativos FROM PUBLIC, anon;
GRANT SELECT ON TABLE public.v_vencimientos_operativos TO authenticated;

COMMENT ON VIEW public.v_vencimientos_operativos IS
  'Vencimientos + catálogo compartido + thumbnails + estado por sucursal + política de donación.';

CREATE OR REPLACE FUNCTION noven_private.puede_reemplazar_imagen_producto(
  p_sucursal_id uuid,
  p_producto_id uuid
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.productos p
    JOIN public.sucursales s
      ON s.id = p_sucursal_id
     AND s.organizacion_id = p.organizacion_id
     AND s.activa = true
    JOIN public.usuario_accesos ua
      ON ua.usuario_id = (SELECT auth.uid())
     AND ua.organizacion_id = p.organizacion_id
     AND ua.activo = true
    WHERE p.id = p_producto_id
      AND (
        ua.rol = 'admin_organizacion'
        OR (ua.rol = 'gerente_zonal' AND ua.zona_id = s.zona_id)
        OR (ua.rol IN ('gerente_sucursal', 'supervisor') AND ua.sucursal_id = s.id)
      )
  );
$$;

REVOKE ALL ON FUNCTION noven_private.puede_reemplazar_imagen_producto(uuid, uuid)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION noven_private.puede_reemplazar_imagen_producto(uuid, uuid)
  TO authenticated;

CREATE OR REPLACE FUNCTION public.modo_imagen_producto_operador(
  p_sucursal_id uuid,
  p_producto_id uuid
)
RETURNS text
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, noven_private, pg_temp
AS $$
DECLARE
  v_imagen text;
BEGIN
  IF (SELECT auth.uid()) IS NULL THEN
    RAISE EXCEPTION 'No autenticado' USING ERRCODE = '28000';
  END IF;

  IF NOT noven_private.puede_ver_producto_sucursal(p_sucursal_id, p_producto_id) THEN
    RETURN 'solo_lectura';
  END IF;

  SELECT p.imagen_url
  INTO v_imagen
  FROM public.productos p
  WHERE p.id = p_producto_id;

  IF NOT FOUND THEN
    RETURN 'solo_lectura';
  END IF;

  IF NULLIF(btrim(COALESCE(v_imagen, '')), '') IS NULL THEN
    RETURN 'agregar';
  END IF;

  IF noven_private.puede_reemplazar_imagen_producto(p_sucursal_id, p_producto_id) THEN
    RETURN 'reemplazar';
  END IF;

  RETURN 'solo_lectura';
END;
$$;

REVOKE ALL ON FUNCTION public.modo_imagen_producto_operador(uuid, uuid)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.modo_imagen_producto_operador(uuid, uuid)
  TO authenticated;

CREATE OR REPLACE FUNCTION noven_private.actualizar_imagen_producto_operador_v2_impl(
  p_sucursal_id uuid,
  p_producto_id uuid,
  p_imagen_url text,
  p_imagen_thumb_url text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_uid uuid := (SELECT auth.uid());
  v_org uuid;
  v_imagen_actual text;
  v_accion text;
  v_fragmento text;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'No autenticado' USING ERRCODE = '28000';
  END IF;

  IF NULLIF(btrim(COALESCE(p_imagen_url, '')), '') IS NULL
     OR NULLIF(btrim(COALESCE(p_imagen_thumb_url, '')), '') IS NULL THEN
    RAISE EXCEPTION 'Las URLs de imagen son obligatorias' USING ERRCODE = '22023';
  END IF;

  SELECT p.organizacion_id, p.imagen_url
  INTO v_org, v_imagen_actual
  FROM public.productos p
  JOIN public.sucursales s
    ON s.id = p_sucursal_id
   AND s.organizacion_id = p.organizacion_id
   AND s.activa = true
  WHERE p.id = p_producto_id
  FOR UPDATE OF p;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Producto/sucursal incompatibles o inexistentes' USING ERRCODE = 'P0002';
  END IF;

  IF NOT noven_private.puede_ver_producto_sucursal(p_sucursal_id, p_producto_id) THEN
    RAISE EXCEPTION 'Sin permiso para gestionar la foto de este producto' USING ERRCODE = '42501';
  END IF;

  v_accion := CASE
    WHEN NULLIF(btrim(COALESCE(v_imagen_actual, '')), '') IS NULL THEN 'agregar'
    ELSE 'reemplazar'
  END;

  IF v_accion = 'reemplazar'
     AND NOT noven_private.puede_reemplazar_imagen_producto(p_sucursal_id, p_producto_id) THEN
    RAISE EXCEPTION 'La foto ya existe; el reemplazo requiere supervisor o gerencia' USING ERRCODE = '42501';
  END IF;

  v_fragmento := '/productos-imagenes/' || v_org::text || '/productos/' || p_producto_id::text || '/';
  IF position(v_fragmento IN p_imagen_url) = 0
     OR position(v_fragmento IN p_imagen_thumb_url) = 0
     OR position('/full.webp' IN p_imagen_url) = 0
     OR position('/thumb.webp' IN p_imagen_thumb_url) = 0 THEN
    RAISE EXCEPTION 'Ruta de imagen fuera del catálogo de la organización' USING ERRCODE = '22023';
  END IF;

  UPDATE public.productos
  SET imagen_url = btrim(p_imagen_url),
      imagen_thumb_url = btrim(p_imagen_thumb_url),
      updated_at = pg_catalog.now()
  WHERE id = p_producto_id
    AND organizacion_id = v_org;

  INSERT INTO public.producto_imagen_cambios(
    organizacion_id,
    producto_id,
    sucursal_id,
    usuario_id,
    accion,
    imagen_url,
    imagen_thumb_url
  ) VALUES (
    v_org,
    p_producto_id,
    p_sucursal_id,
    v_uid,
    v_accion,
    btrim(p_imagen_url),
    btrim(p_imagen_thumb_url)
  );
END;
$$;

REVOKE ALL ON FUNCTION noven_private.actualizar_imagen_producto_operador_v2_impl(uuid, uuid, text, text)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION noven_private.actualizar_imagen_producto_operador_v2_impl(uuid, uuid, text, text)
  TO authenticated;

CREATE OR REPLACE FUNCTION public.actualizar_imagen_producto_operador_v2(
  p_sucursal_id uuid,
  p_producto_id uuid,
  p_imagen_url text,
  p_imagen_thumb_url text
)
RETURNS void
LANGUAGE sql
SECURITY INVOKER
SET search_path = ''
AS $$
  SELECT noven_private.actualizar_imagen_producto_operador_v2_impl(
    p_sucursal_id,
    p_producto_id,
    p_imagen_url,
    p_imagen_thumb_url
  );
$$;

REVOKE ALL ON FUNCTION public.actualizar_imagen_producto_operador_v2(uuid, uuid, text, text)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.actualizar_imagen_producto_operador_v2(uuid, uuid, text, text)
  TO authenticated;

-- Helpers para RLS de Storage. La ruta V2 es:
-- <organizacion_uuid>/productos/<producto_uuid>/(full|thumb).webp
CREATE OR REPLACE FUNCTION noven_private.puede_insertar_imagen_catalogo_storage(p_name text)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_org uuid;
  v_producto uuid;
  v_archivo text;
BEGIN
  IF (SELECT auth.uid()) IS NULL THEN RETURN false; END IF;
  IF pg_catalog.split_part(p_name, '/', 2) <> 'productos' THEN RETURN false; END IF;
  v_archivo := pg_catalog.split_part(p_name, '/', 4);
  IF v_archivo NOT IN ('full.webp', 'thumb.webp') THEN RETURN false; END IF;

  BEGIN
    v_org := pg_catalog.split_part(p_name, '/', 1)::uuid;
    v_producto := pg_catalog.split_part(p_name, '/', 3)::uuid;
  EXCEPTION WHEN invalid_text_representation THEN
    RETURN false;
  END;

  RETURN EXISTS (
    SELECT 1
    FROM public.productos p
    JOIN public.producto_sucursal ps
      ON ps.producto_id = p.id
     AND ps.organizacion_id = p.organizacion_id
    WHERE p.id = v_producto
      AND p.organizacion_id = v_org
      AND noven_private.puede_ver_producto_sucursal(ps.sucursal_id, p.id)
  );
END;
$$;

REVOKE ALL ON FUNCTION noven_private.puede_insertar_imagen_catalogo_storage(text)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION noven_private.puede_insertar_imagen_catalogo_storage(text)
  TO authenticated;

CREATE OR REPLACE FUNCTION noven_private.puede_actualizar_imagen_catalogo_storage(p_name text)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_org uuid;
  v_producto uuid;
  v_archivo text;
  v_imagen_actual text;
BEGIN
  IF NOT noven_private.puede_insertar_imagen_catalogo_storage(p_name) THEN RETURN false; END IF;

  v_archivo := pg_catalog.split_part(p_name, '/', 4);
  BEGIN
    v_org := pg_catalog.split_part(p_name, '/', 1)::uuid;
    v_producto := pg_catalog.split_part(p_name, '/', 3)::uuid;
  EXCEPTION WHEN invalid_text_representation THEN
    RETURN false;
  END;

  SELECT p.imagen_url
  INTO v_imagen_actual
  FROM public.productos p
  WHERE p.id = v_producto
    AND p.organizacion_id = v_org;

  -- Permite reintentar una primera carga que dejó el objeto creado pero aún no
  -- actualizó el catálogo. Una vez que hay foto oficial, sólo roles elevados.
  IF NULLIF(btrim(COALESCE(v_imagen_actual, '')), '') IS NULL THEN RETURN true; END IF;

  RETURN EXISTS (
    SELECT 1
    FROM public.usuario_accesos ua
    WHERE ua.usuario_id = (SELECT auth.uid())
      AND ua.organizacion_id = v_org
      AND ua.activo = true
      AND ua.rol IN ('admin_organizacion', 'gerente_zonal', 'gerente_sucursal', 'supervisor')
  );
END;
$$;

REVOKE ALL ON FUNCTION noven_private.puede_actualizar_imagen_catalogo_storage(text)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION noven_private.puede_actualizar_imagen_catalogo_storage(text)
  TO authenticated;

COMMIT;
