-- =============================================================================
-- NOVEN · APRENDIZAJE GLOBAL DE CATÁLOGO V1
--
-- Un cod_art nuevo se clasifica UNA sola vez por organización. Todas las
-- sucursales que ya lo detectaron conservan su stock/VMD y se benefician de la
-- clasificación sin volver a subir el CSV.
-- =============================================================================

BEGIN;

CREATE TABLE public.productos_pendientes_catalogo (
  id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organizacion_id     uuid        NOT NULL REFERENCES public.organizaciones(id) ON DELETE CASCADE,
  cod_art             text        NOT NULL,
  descripcion         text        NOT NULL,
  marca               text,
  gramaje             text,
  producto_id         uuid,
  estado              text        NOT NULL DEFAULT 'pendiente'
                                  CHECK (estado IN ('pendiente', 'resuelto', 'descartado')),
  familia_id_resuelta uuid,
  clasificado_por     uuid        REFERENCES public.usuarios(id) ON DELETE SET NULL,
  clasificado_at      timestamptz,
  first_detected_at   timestamptz NOT NULL DEFAULT now(),
  last_detected_at    timestamptz NOT NULL DEFAULT now(),
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT productos_pendientes_catalogo_org_cod_uk
    UNIQUE (organizacion_id, cod_art),
  CONSTRAINT productos_pendientes_catalogo_producto_org_fk
    FOREIGN KEY (producto_id, organizacion_id)
    REFERENCES public.productos(id, organizacion_id)
    ON DELETE RESTRICT,
  CONSTRAINT productos_pendientes_catalogo_familia_org_fk
    FOREIGN KEY (familia_id_resuelta, organizacion_id)
    REFERENCES public.familias(id, organizacion_id)
    ON DELETE RESTRICT,
  CONSTRAINT productos_pendientes_catalogo_resolucion_check CHECK (
    (estado = 'resuelto' AND familia_id_resuelta IS NOT NULL AND clasificado_at IS NOT NULL)
    OR estado <> 'resuelto'
  )
);

CREATE INDEX productos_pendientes_catalogo_estado_idx
  ON public.productos_pendientes_catalogo(organizacion_id, estado, last_detected_at DESC);
CREATE INDEX productos_pendientes_catalogo_producto_idx
  ON public.productos_pendientes_catalogo(producto_id)
  WHERE producto_id IS NOT NULL;

CREATE TRIGGER productos_pendientes_catalogo_updated_at
  BEFORE UPDATE ON public.productos_pendientes_catalogo
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.producto_pendiente_detecciones (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pendiente_id        uuid        NOT NULL REFERENCES public.productos_pendientes_catalogo(id) ON DELETE CASCADE,
  organizacion_id     uuid        NOT NULL REFERENCES public.organizaciones(id) ON DELETE CASCADE,
  sucursal_id         uuid        NOT NULL,
  importacion_id      uuid        NOT NULL,
  stock               integer     NOT NULL,
  venta_media_diaria  numeric     NOT NULL DEFAULT 0,
  fila_origen         integer,
  detected_at         timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT producto_pendiente_detecciones_sucursal_org_fk
    FOREIGN KEY (sucursal_id, organizacion_id)
    REFERENCES public.sucursales(id, organizacion_id)
    ON DELETE CASCADE,
  CONSTRAINT producto_pendiente_detecciones_import_scope_fk
    FOREIGN KEY (importacion_id, organizacion_id, sucursal_id)
    REFERENCES public.importaciones(id, organizacion_id, sucursal_id)
    ON DELETE RESTRICT,
  CONSTRAINT producto_pendiente_detecciones_pendiente_import_uk
    UNIQUE (pendiente_id, importacion_id),
  CONSTRAINT producto_pendiente_detecciones_fila_check
    CHECK (fila_origen IS NULL OR fila_origen > 0)
);

CREATE INDEX producto_pendiente_detecciones_pendiente_fecha_idx
  ON public.producto_pendiente_detecciones(pendiente_id, detected_at DESC);
CREATE INDEX producto_pendiente_detecciones_sucursal_fecha_idx
  ON public.producto_pendiente_detecciones(sucursal_id, detected_at DESC);

ALTER TABLE public.productos_pendientes_catalogo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.producto_pendiente_detecciones ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.productos_pendientes_catalogo FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.producto_pendiente_detecciones FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.productos_pendientes_catalogo TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.producto_pendiente_detecciones TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.producto_pendiente_detecciones_id_seq TO service_role;

-- -----------------------------------------------------------------------------
-- V2 del import masivo: reutiliza la transacción V1 y agrega aprendizaje global.
-- Si esta parte falla, PostgreSQL revierte también la llamada V1.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.aplicar_importacion_glaciar_masiva_v2(
  p_sucursal_id uuid,
  p_usuario_id uuid,
  p_codigo_sucursal_fuente text,
  p_nombre_archivo text,
  p_archivo_sha256 text,
  p_filas_total integer,
  p_filas_validas integer,
  p_filas_descartadas integer,
  p_items jsonb,
  p_fecha_reporte date DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_resultado jsonb;
  v_importacion_id uuid;
  v_org_id uuid;
  v_pendientes integer := 0;
BEGIN
  SELECT public.aplicar_importacion_glaciar_masiva(
    p_sucursal_id,
    p_usuario_id,
    p_codigo_sucursal_fuente,
    p_nombre_archivo,
    p_archivo_sha256,
    p_filas_total,
    p_filas_validas,
    p_filas_descartadas,
    p_items,
    p_fecha_reporte
  ) INTO v_resultado;

  IF COALESCE((v_resultado->>'duplicada')::boolean, false) THEN
    RETURN v_resultado;
  END IF;

  v_importacion_id := (v_resultado->>'importacion_id')::uuid;

  SELECT organizacion_id INTO v_org_id
  FROM public.importaciones
  WHERE id = v_importacion_id;

  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'No se pudo resolver la organización de la importación';
  END IF;

  -- Upsert global de cada código que todavía no puede rutearse. Si otra sucursal
  -- ya lo había detectado, sólo refrescamos metadatos y last_detected_at.
  WITH entrada AS (
    SELECT
      btrim(x.cod_art) AS cod_art,
      NULLIF(btrim(x.descripcion), '') AS descripcion,
      NULLIF(btrim(x.marca), '') AS marca,
      NULLIF(btrim(x.gramaje), '') AS gramaje
    FROM jsonb_to_recordset(p_items) AS x(
      cod_art text,
      descripcion text,
      marca text,
      gramaje text,
      stock integer,
      venta_media_diaria numeric,
      fila_origen integer
    )
  ), pendientes AS (
    SELECT e.*, p.id AS producto_id
    FROM entrada e
    LEFT JOIN public.productos p
      ON p.organizacion_id = v_org_id
     AND p.cod_art = e.cod_art
     AND p.activo = true
    WHERE p.id IS NULL OR p.familia_id IS NULL
  )
  INSERT INTO public.productos_pendientes_catalogo (
    organizacion_id,
    cod_art,
    descripcion,
    marca,
    gramaje,
    producto_id,
    last_detected_at
  )
  SELECT
    v_org_id,
    pe.cod_art,
    COALESCE(pe.descripcion, pe.cod_art),
    pe.marca,
    pe.gramaje,
    pe.producto_id,
    now()
  FROM pendientes pe
  ON CONFLICT (organizacion_id, cod_art)
  DO UPDATE SET
    descripcion = COALESCE(NULLIF(EXCLUDED.descripcion, ''), public.productos_pendientes_catalogo.descripcion),
    marca = COALESCE(EXCLUDED.marca, public.productos_pendientes_catalogo.marca),
    gramaje = COALESCE(EXCLUDED.gramaje, public.productos_pendientes_catalogo.gramaje),
    producto_id = COALESCE(public.productos_pendientes_catalogo.producto_id, EXCLUDED.producto_id),
    last_detected_at = now()
  WHERE public.productos_pendientes_catalogo.estado = 'pendiente';

  -- Una detección por importación. Así preservamos todas las sucursales y todos
  -- los archivos que observaron el artículo antes de que fuera clasificado.
  WITH entrada AS (
    SELECT
      btrim(x.cod_art) AS cod_art,
      x.stock,
      COALESCE(x.venta_media_diaria, 0) AS venta_media_diaria,
      x.fila_origen
    FROM jsonb_to_recordset(p_items) AS x(
      cod_art text,
      descripcion text,
      marca text,
      gramaje text,
      stock integer,
      venta_media_diaria numeric,
      fila_origen integer
    )
  )
  INSERT INTO public.producto_pendiente_detecciones (
    pendiente_id,
    organizacion_id,
    sucursal_id,
    importacion_id,
    stock,
    venta_media_diaria,
    fila_origen
  )
  SELECT
    pp.id,
    v_org_id,
    p_sucursal_id,
    v_importacion_id,
    e.stock,
    e.venta_media_diaria,
    e.fila_origen
  FROM entrada e
  JOIN public.productos_pendientes_catalogo pp
    ON pp.organizacion_id = v_org_id
   AND pp.cod_art = e.cod_art
   AND pp.estado = 'pendiente'
  LEFT JOIN public.productos p
    ON p.organizacion_id = v_org_id
   AND p.cod_art = e.cod_art
   AND p.activo = true
  WHERE p.id IS NULL OR p.familia_id IS NULL
  ON CONFLICT (pendiente_id, importacion_id) DO NOTHING;

  SELECT count(*) INTO v_pendientes
  FROM public.productos_pendientes_catalogo pp
  WHERE pp.organizacion_id = v_org_id
    AND pp.estado = 'pendiente';

  RETURN v_resultado || jsonb_build_object('pendientes_organizacion', v_pendientes);
END;
$$;

REVOKE ALL ON FUNCTION public.aplicar_importacion_glaciar_masiva_v2(
  uuid, uuid, text, text, text, integer, integer, integer, jsonb, date
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.aplicar_importacion_glaciar_masiva_v2(
  uuid, uuid, text, text, text, integer, integer, integer, jsonb, date
) TO service_role;

-- -----------------------------------------------------------------------------
-- Listado server-only de pendientes visibles para un usuario de gestión.
-- Un gerente puede resolver un artículo si éste fue detectado en al menos una
-- sucursal dentro de su alcance. La clasificación resultante es global al tenant.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.listar_productos_pendientes_catalogo(
  p_usuario_id uuid
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
  SELECT COALESCE(jsonb_agg(item ORDER BY last_detected_at DESC), '[]'::jsonb)
  FROM (
    SELECT jsonb_build_object(
      'id', pp.id,
      'organizacion_id', pp.organizacion_id,
      'cod_art', pp.cod_art,
      'descripcion', pp.descripcion,
      'marca', pp.marca,
      'gramaje', pp.gramaje,
      'producto_id', pp.producto_id,
      'first_detected_at', pp.first_detected_at,
      'last_detected_at', pp.last_detected_at,
      'detecciones', count(DISTINCT d.importacion_id),
      'sucursales', COALESCE(
        jsonb_agg(DISTINCT jsonb_build_object(
          'id', s.id,
          'codigo', s.codigo,
          'nombre', s.nombre
        )),
        '[]'::jsonb
      )
    ) AS item,
    pp.last_detected_at
    FROM public.productos_pendientes_catalogo pp
    JOIN public.producto_pendiente_detecciones d ON d.pendiente_id = pp.id
    JOIN public.sucursales s ON s.id = d.sucursal_id
    WHERE pp.estado = 'pendiente'
      AND EXISTS (
        SELECT 1
        FROM public.usuario_accesos ua
        WHERE ua.usuario_id = p_usuario_id
          AND ua.organizacion_id = pp.organizacion_id
          AND ua.activo = true
          AND ua.rol <> 'operador'
          AND (
            ua.rol = 'admin_organizacion'
            OR (ua.rol = 'gerente_zonal' AND ua.zona_id = s.zona_id)
            OR (ua.rol IN ('gerente_sucursal', 'supervisor') AND ua.sucursal_id = s.id)
          )
      )
    GROUP BY pp.id, pp.organizacion_id, pp.cod_art, pp.descripcion, pp.marca,
             pp.gramaje, pp.producto_id, pp.first_detected_at, pp.last_detected_at
  ) q;
$$;

REVOKE ALL ON FUNCTION public.listar_productos_pendientes_catalogo(uuid)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.listar_productos_pendientes_catalogo(uuid)
  TO service_role;

-- -----------------------------------------------------------------------------
-- Resolución global. Bloquea la fila para evitar doble clasificación concurrente.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.resolver_producto_pendiente_catalogo(
  p_pendiente_id uuid,
  p_familia_id uuid,
  p_usuario_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_p public.productos_pendientes_catalogo%ROWTYPE;
  v_producto_id uuid;
  v_familia_org uuid;
  v_sucursales_afectadas integer := 0;
  v_legacy_091 constant uuid := '00000000-0000-0000-0000-000000000001'::uuid;
BEGIN
  SELECT * INTO v_p
  FROM public.productos_pendientes_catalogo
  WHERE id = p_pendiente_id
  FOR UPDATE;

  IF v_p.id IS NULL THEN
    RAISE EXCEPTION 'Producto pendiente inexistente';
  END IF;

  IF v_p.estado = 'resuelto' THEN
    RETURN jsonb_build_object(
      'ya_resuelto', true,
      'producto_id', v_p.producto_id,
      'familia_id', v_p.familia_id_resuelta
    );
  END IF;

  IF v_p.estado <> 'pendiente' THEN
    RAISE EXCEPTION 'El producto pendiente no está disponible para clasificación';
  END IF;

  SELECT organizacion_id INTO v_familia_org
  FROM public.familias
  WHERE id = p_familia_id;

  IF v_familia_org IS DISTINCT FROM v_p.organizacion_id THEN
    RAISE EXCEPTION 'La familia no pertenece a la organización del producto';
  END IF;

  -- El usuario debe gestionar al menos una sucursal donde el artículo apareció.
  IF NOT EXISTS (
    SELECT 1
    FROM public.producto_pendiente_detecciones d
    JOIN public.sucursales s ON s.id = d.sucursal_id
    JOIN public.usuario_accesos ua
      ON ua.usuario_id = p_usuario_id
     AND ua.organizacion_id = v_p.organizacion_id
     AND ua.activo = true
    WHERE d.pendiente_id = v_p.id
      AND ua.rol <> 'operador'
      AND (
        ua.rol = 'admin_organizacion'
        OR (ua.rol = 'gerente_zonal' AND ua.zona_id = s.zona_id)
        OR (ua.rol IN ('gerente_sucursal', 'supervisor') AND ua.sucursal_id = s.id)
      )
  ) THEN
    RAISE EXCEPTION 'El usuario no tiene alcance para clasificar este producto';
  END IF;

  v_producto_id := v_p.producto_id;

  IF v_producto_id IS NOT NULL THEN
    -- Producto ya existente pero sin familia.
    UPDATE public.productos
    SET familia_id = p_familia_id, updated_at = now()
    WHERE id = v_producto_id
      AND organizacion_id = v_p.organizacion_id
      AND familia_id IS NULL;

    IF NOT FOUND THEN
      -- Otro proceso pudo haberlo clasificado por fuera de esta bandeja.
      SELECT id INTO v_producto_id
      FROM public.productos
      WHERE id = v_p.producto_id
        AND organizacion_id = v_p.organizacion_id
        AND familia_id = p_familia_id;
      IF v_producto_id IS NULL THEN
        RAISE EXCEPTION 'El producto ya tiene una clasificación diferente; requiere revisión administrativa';
      END IF;
    END IF;
  ELSE
    -- Alta global. Evita que el bridge legacy invente 091 si el producto nació en
    -- otra tienda; más abajo se crean exclusivamente los estados detectados.
    PERFORM set_config('noven.skip_legacy_bridge', '1', true);

    INSERT INTO public.productos (
      organizacion_id,
      cod_art,
      descripcion,
      marca,
      gramaje,
      categoria,
      familia_id,
      stock_actual,
      venta_media_diaria,
      activo
    ) VALUES (
      v_p.organizacion_id,
      v_p.cod_art,
      v_p.descripcion,
      v_p.marca,
      v_p.gramaje,
      'OTRO',
      p_familia_id,
      0,
      0,
      true
    )
    ON CONFLICT (organizacion_id, cod_art)
    DO NOTHING
    RETURNING id INTO v_producto_id;

    IF v_producto_id IS NULL THEN
      SELECT id INTO v_producto_id
      FROM public.productos
      WHERE organizacion_id = v_p.organizacion_id
        AND cod_art = v_p.cod_art
        AND activo = true;

      IF v_producto_id IS NULL THEN
        RAISE EXCEPTION 'No se pudo crear ni recuperar el producto global';
      END IF;

      UPDATE public.productos
      SET familia_id = p_familia_id, updated_at = now()
      WHERE id = v_producto_id
        AND familia_id IS NULL;

      IF NOT FOUND AND NOT EXISTS (
        SELECT 1 FROM public.productos
        WHERE id = v_producto_id AND familia_id = p_familia_id
      ) THEN
        RAISE EXCEPTION 'El producto fue clasificado simultáneamente con otra familia';
      END IF;
    END IF;
  END IF;

  -- Backfill histórico: una vez que existe producto_id, todos los snapshots que
  -- antes eran pendientes pasan a ser evidencia normal del catálogo.
  INSERT INTO public.producto_snapshots (
    importacion_id,
    organizacion_id,
    sucursal_id,
    producto_id,
    stock,
    venta_media_diaria,
    fila_origen,
    captured_at
  )
  SELECT
    d.importacion_id,
    d.organizacion_id,
    d.sucursal_id,
    v_producto_id,
    d.stock,
    d.venta_media_diaria,
    d.fila_origen,
    d.detected_at
  FROM public.producto_pendiente_detecciones d
  WHERE d.pendiente_id = v_p.id
  ON CONFLICT (importacion_id, producto_id) DO NOTHING;

  -- Estado actual: la detección más reciente de CADA sucursal gana.
  WITH ultimas AS (
    SELECT DISTINCT ON (d.sucursal_id)
      d.organizacion_id,
      d.sucursal_id,
      d.stock,
      d.venta_media_diaria,
      d.detected_at
    FROM public.producto_pendiente_detecciones d
    WHERE d.pendiente_id = v_p.id
    ORDER BY d.sucursal_id, d.detected_at DESC, d.id DESC
  )
  INSERT INTO public.producto_sucursal (
    organizacion_id,
    producto_id,
    sucursal_id,
    stock_actual,
    venta_media_diaria,
    fecha_ultima_importacion
  )
  SELECT
    u.organizacion_id,
    v_producto_id,
    u.sucursal_id,
    u.stock,
    u.venta_media_diaria,
    u.detected_at
  FROM ultimas u
  ON CONFLICT (producto_id, sucursal_id)
  DO UPDATE SET
    stock_actual = EXCLUDED.stock_actual,
    venta_media_diaria = EXCLUDED.venta_media_diaria,
    fecha_ultima_importacion = EXCLUDED.fecha_ultima_importacion,
    updated_at = now();

  SELECT count(DISTINCT sucursal_id) INTO v_sucursales_afectadas
  FROM public.producto_pendiente_detecciones
  WHERE pendiente_id = v_p.id;

  -- Mientras 091 siga leyendo columnas legacy, reflejamos SU último estado si
  -- ese producto fue detectado allí. Nunca usamos datos de otra sucursal.
  PERFORM set_config('noven.skip_legacy_bridge', '1', true);
  UPDATE public.productos p
  SET
    stock_actual = x.stock,
    venta_media_diaria = x.venta_media_diaria,
    updated_at = now()
  FROM (
    SELECT d.stock, d.venta_media_diaria
    FROM public.producto_pendiente_detecciones d
    WHERE d.pendiente_id = v_p.id
      AND d.sucursal_id = v_legacy_091
    ORDER BY d.detected_at DESC, d.id DESC
    LIMIT 1
  ) x
  WHERE p.id = v_producto_id;

  UPDATE public.productos_pendientes_catalogo
  SET
    producto_id = v_producto_id,
    estado = 'resuelto',
    familia_id_resuelta = p_familia_id,
    clasificado_por = p_usuario_id,
    clasificado_at = now(),
    updated_at = now()
  WHERE id = v_p.id;

  RETURN jsonb_build_object(
    'ya_resuelto', false,
    'producto_id', v_producto_id,
    'familia_id', p_familia_id,
    'sucursales_afectadas', v_sucursales_afectadas
  );
END;
$$;

REVOKE ALL ON FUNCTION public.resolver_producto_pendiente_catalogo(uuid, uuid, uuid)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.resolver_producto_pendiente_catalogo(uuid, uuid, uuid)
  TO service_role;

COMMENT ON TABLE public.productos_pendientes_catalogo IS
  'Bandeja global por organización: un cod_art se clasifica una sola vez para toda la cadena.';
COMMENT ON TABLE public.producto_pendiente_detecciones IS
  'Observaciones por sucursal/importación de un cod_art aún no clasificado.';

COMMIT;
