-- =============================================================================
-- NOVEN · POLÍTICAS DE DONACIÓN + SEGUIMIENTO RAG V1
--
-- Objetivos:
--   1. El umbral de retiro/donación deja de ser global: se configura por sector.
--   2. Conservar cada observación del stock comprometido realizada por operador.
--   3. Conservar cada aplicación/cambio de RAG (Retiro Anticipado de Góndola).
--   4. Exponer un seguimiento derivado que compare velocidad observada contra la
--      velocidad necesaria para vender antes del retiro obligatorio.
--
-- No se aplica automáticamente a producción desde esta rama.
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 1. POLÍTICA DE DONACIÓN POR SECTOR
-- -----------------------------------------------------------------------------
ALTER TABLE public.sectores
  ADD COLUMN IF NOT EXISTS dias_donacion integer;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sectores_dias_donacion_rango'
      AND conrelid = 'public.sectores'::regclass
  ) THEN
    ALTER TABLE public.sectores
      ADD CONSTRAINT sectores_dias_donacion_rango
      CHECK (dias_donacion IS NULL OR dias_donacion BETWEEN 1 AND 90);
  END IF;
END;
$$;

-- Sectores hoy confirmados por negocio.
-- Perecederos confirmados existentes: 2 días.
UPDATE public.sectores
SET dias_donacion = 2
WHERE upper(btrim(nombre)) IN ('LACTEOS', 'PANADERIA');

-- No perecederos confirmados existentes: 10 días.
UPDATE public.sectores
SET dias_donacion = 10
WHERE upper(btrim(nombre)) IN (
  'ALMACEN', 'BEBIDAS', 'LIMPIEZA', 'PERFUMERIA',
  'NO COMESTIBLES', 'ELECTRO', 'TEXTIL'
);

-- FIAMBRES e INSUMOS quedan deliberadamente sin auto-clasificar: no inventar
-- una política que negocio todavía no confirmó para esos nombres concretos.
-- Sectores futuros (Carnicería, Verdulería, Rotisería, Congelados, etc.) deben
-- declarar dias_donacion al crearse/configurarse.

COMMENT ON COLUMN public.sectores.dias_donacion IS
  'Días antes del vencimiento en que el producto debe retirarse de venta y pasar a donación. Configuración de negocio por sector.';

-- -----------------------------------------------------------------------------
-- 2. IDENTIDAD COMPUESTA DEL VENCIMIENTO PARA HISTÓRICOS
-- -----------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'vencimientos_id_producto_sucursal_uk'
      AND conrelid = 'public.vencimientos'::regclass
  ) THEN
    ALTER TABLE public.vencimientos
      ADD CONSTRAINT vencimientos_id_producto_sucursal_uk
      UNIQUE (id, producto_id, sucursal_id);
  END IF;
END;
$$;

-- -----------------------------------------------------------------------------
-- 3. OBSERVACIONES DEL OPERADOR — historial inmutable de cantidad comprometida
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.vencimiento_observaciones (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizacion_id       uuid        NOT NULL REFERENCES public.organizaciones(id) ON DELETE RESTRICT,
  sucursal_id           uuid        NOT NULL,
  producto_id           uuid        NOT NULL,
  vencimiento_id        uuid        NOT NULL,
  usuario_id            uuid        NOT NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
  cantidad_comprometida numeric     NOT NULL CHECK (cantidad_comprometida >= 0),
  observada_at          timestamptz NOT NULL DEFAULT now(),
  nota                  text,
  created_at            timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT venc_obs_sucursal_org_fk
    FOREIGN KEY (sucursal_id, organizacion_id)
    REFERENCES public.sucursales(id, organizacion_id)
    ON DELETE RESTRICT,

  CONSTRAINT venc_obs_producto_org_fk
    FOREIGN KEY (producto_id, organizacion_id)
    REFERENCES public.productos(id, organizacion_id)
    ON DELETE RESTRICT,

  CONSTRAINT venc_obs_vencimiento_scope_fk
    FOREIGN KEY (vencimiento_id, producto_id, sucursal_id)
    REFERENCES public.vencimientos(id, producto_id, sucursal_id)
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS venc_obs_vencimiento_fecha_idx
  ON public.vencimiento_observaciones(vencimiento_id, observada_at DESC);
CREATE INDEX IF NOT EXISTS venc_obs_sucursal_fecha_idx
  ON public.vencimiento_observaciones(sucursal_id, observada_at DESC);
CREATE INDEX IF NOT EXISTS venc_obs_producto_org_idx
  ON public.vencimiento_observaciones(producto_id, organizacion_id);

ALTER TABLE public.vencimiento_observaciones ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.vencimiento_observaciones FROM PUBLIC, anon;
GRANT SELECT, INSERT ON TABLE public.vencimiento_observaciones TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.vencimiento_observaciones_id_seq TO authenticated;

DROP POLICY IF EXISTS venc_obs_select_scope ON public.vencimiento_observaciones;
CREATE POLICY venc_obs_select_scope
  ON public.vencimiento_observaciones
  FOR SELECT TO authenticated
  USING (noven_private.puede_ver_producto_sucursal(sucursal_id, producto_id));

DROP POLICY IF EXISTS venc_obs_insert_scope ON public.vencimiento_observaciones;
CREATE POLICY venc_obs_insert_scope
  ON public.vencimiento_observaciones
  FOR INSERT TO authenticated
  WITH CHECK (
    usuario_id = (SELECT auth.uid())
    AND noven_private.puede_ver_producto_sucursal(sucursal_id, producto_id)
  );

COMMENT ON TABLE public.vencimiento_observaciones IS
  'Serie temporal inmutable de cantidad comprometida observada físicamente por el operador.';

-- -----------------------------------------------------------------------------
-- 4. INTERVENCIONES RAG — cada porcentaje aplicado es un evento nuevo
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.intervenciones_rag (
  id                              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organizacion_id                 uuid        NOT NULL REFERENCES public.organizaciones(id) ON DELETE RESTRICT,
  sucursal_id                     uuid        NOT NULL,
  producto_id                     uuid        NOT NULL,
  vencimiento_id                  uuid        NOT NULL,
  usuario_id                      uuid        NOT NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
  porcentaje_descuento            numeric(5,2) NOT NULL CHECK (porcentaje_descuento > 0 AND porcentaje_descuento <= 100),
  cantidad_comprometida_al_aplicar numeric      NOT NULL CHECK (cantidad_comprometida_al_aplicar >= 0),
  vmd_glaciar_al_aplicar          numeric,
  aplicado_at                     timestamptz NOT NULL DEFAULT now(),
  nota                            text,
  created_at                      timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT rag_sucursal_org_fk
    FOREIGN KEY (sucursal_id, organizacion_id)
    REFERENCES public.sucursales(id, organizacion_id)
    ON DELETE RESTRICT,

  CONSTRAINT rag_producto_org_fk
    FOREIGN KEY (producto_id, organizacion_id)
    REFERENCES public.productos(id, organizacion_id)
    ON DELETE RESTRICT,

  CONSTRAINT rag_vencimiento_scope_fk
    FOREIGN KEY (vencimiento_id, producto_id, sucursal_id)
    REFERENCES public.vencimientos(id, producto_id, sucursal_id)
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS rag_vencimiento_fecha_idx
  ON public.intervenciones_rag(vencimiento_id, aplicado_at DESC);
CREATE INDEX IF NOT EXISTS rag_sucursal_fecha_idx
  ON public.intervenciones_rag(sucursal_id, aplicado_at DESC);
CREATE INDEX IF NOT EXISTS rag_producto_org_idx
  ON public.intervenciones_rag(producto_id, organizacion_id);

ALTER TABLE public.intervenciones_rag ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.intervenciones_rag FROM PUBLIC, anon;
GRANT SELECT, INSERT ON TABLE public.intervenciones_rag TO authenticated;

DROP POLICY IF EXISTS rag_select_scope ON public.intervenciones_rag;
CREATE POLICY rag_select_scope
  ON public.intervenciones_rag
  FOR SELECT TO authenticated
  USING (noven_private.puede_ver_producto_sucursal(sucursal_id, producto_id));

DROP POLICY IF EXISTS rag_insert_scope ON public.intervenciones_rag;
CREATE POLICY rag_insert_scope
  ON public.intervenciones_rag
  FOR INSERT TO authenticated
  WITH CHECK (
    usuario_id = (SELECT auth.uid())
    AND noven_private.puede_ver_producto_sucursal(sucursal_id, producto_id)
  );

COMMENT ON TABLE public.intervenciones_rag IS
  'Historial append-only de RAG. Un cambio 30%→50% crea una nueva fila y conserva la intervención anterior.';

-- -----------------------------------------------------------------------------
-- 5. VISTA DE SEGUIMIENTO RAG ACTUAL
--
-- Prioridad de señales:
--   - La observación física del operador mide la respuesta rápida del lote.
--   - La VMD de Glaciar sigue siendo tendencia histórica/contexto y puede
--     confirmar suficiencia cuando todavía no existe control posterior.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW public.v_seguimiento_rag_actual
WITH (security_invoker = true)
AS
SELECT
  v.id AS vencimiento_id,
  p.organizacion_id,
  v.sucursal_id,
  v.producto_id,
  p.descripcion,
  p.familia_id,
  f.sector_id,
  s.nombre AS sector_nombre,
  s.dias_donacion,
  v.fecha_vencimiento,
  (v.fecha_vencimiento - CURRENT_DATE) AS dias_hasta_vencimiento,
  GREATEST((v.fecha_vencimiento - CURRENT_DATE) - COALESCE(s.dias_donacion, 10), 0) AS dias_comerciales_restantes,
  ps.venta_media_diaria AS vmd_glaciar_actual,
  ps.fecha_ultima_importacion,

  rag.id AS rag_id,
  rag.porcentaje_descuento AS rag_porcentaje,
  rag.aplicado_at AS rag_aplicado_at,
  rag.cantidad_comprometida_al_aplicar AS cantidad_base_rag,
  rag.vmd_glaciar_al_aplicar,

  obs.id AS observacion_id,
  obs.observada_at,
  obs.cantidad_comprometida AS cantidad_observada,
  COALESCE(obs.cantidad_comprometida, v.cantidad) AS cantidad_actual_estimacion,

  CASE
    WHEN rag.id IS NULL OR obs.id IS NULL THEN NULL
    ELSE GREATEST(rag.cantidad_comprometida_al_aplicar - obs.cantidad_comprometida, 0)
  END AS unidades_vendidas_observadas,

  CASE
    WHEN rag.id IS NULL OR obs.id IS NULL OR obs.observada_at <= rag.aplicado_at THEN NULL
    ELSE EXTRACT(EPOCH FROM (obs.observada_at - rag.aplicado_at)) / 86400.0
  END AS dias_observados,

  CASE
    WHEN rag.id IS NULL OR obs.id IS NULL OR obs.observada_at <= rag.aplicado_at THEN NULL
    ELSE GREATEST(rag.cantidad_comprometida_al_aplicar - obs.cantidad_comprometida, 0)
         / NULLIF(EXTRACT(EPOCH FROM (obs.observada_at - rag.aplicado_at)) / 86400.0, 0)
  END AS velocidad_observada,

  CASE
    WHEN GREATEST((v.fecha_vencimiento - CURRENT_DATE) - COALESCE(s.dias_donacion, 10), 0) <= 0 THEN NULL
    ELSE COALESCE(obs.cantidad_comprometida, v.cantidad)
         / GREATEST((v.fecha_vencimiento - CURRENT_DATE) - COALESCE(s.dias_donacion, 10), 0)::numeric
  END AS velocidad_necesaria,

  CASE
    WHEN (v.fecha_vencimiento - CURRENT_DATE) <= 0 THEN 'decomiso'
    WHEN (v.fecha_vencimiento - CURRENT_DATE) <= COALESCE(s.dias_donacion, 10) THEN 'donacion'
    WHEN rag.id IS NULL THEN 'sin_rag'
    WHEN obs.id IS NULL THEN
      CASE
        WHEN GREATEST((v.fecha_vencimiento - CURRENT_DATE) - COALESCE(s.dias_donacion, 10), 0) > 0
         AND ps.venta_media_diaria >= (
           v.cantidad / GREATEST((v.fecha_vencimiento - CURRENT_DATE) - COALESCE(s.dias_donacion, 10), 1)::numeric
         )
        THEN 'efectivo_por_vmd'
        ELSE 'pendiente_control_operador'
      END
    WHEN obs.cantidad_comprometida > rag.cantidad_comprometida_al_aplicar THEN 'dato_a_revisar'
    WHEN obs.cantidad_comprometida = 0 THEN 'efectivo'
    WHEN obs.cantidad_comprometida = rag.cantidad_comprometida_al_aplicar THEN 'sin_movimiento'
    WHEN obs.observada_at <= rag.aplicado_at THEN 'pendiente_control_operador'
    WHEN (
      GREATEST(rag.cantidad_comprometida_al_aplicar - obs.cantidad_comprometida, 0)
      / NULLIF(EXTRACT(EPOCH FROM (obs.observada_at - rag.aplicado_at)) / 86400.0, 0)
    ) >= (
      obs.cantidad_comprometida
      / GREATEST((v.fecha_vencimiento - CURRENT_DATE) - COALESCE(s.dias_donacion, 10), 1)::numeric
    ) THEN 'efectivo'
    ELSE 'insuficiente'
  END AS estado_seguimiento_rag

FROM public.vencimientos v
JOIN public.productos p
  ON p.id = v.producto_id
JOIN public.producto_sucursal ps
  ON ps.producto_id = v.producto_id
 AND ps.sucursal_id = v.sucursal_id
 AND ps.organizacion_id = p.organizacion_id
LEFT JOIN public.familias f
  ON f.id = p.familia_id
 AND f.organizacion_id = p.organizacion_id
LEFT JOIN public.sectores s
  ON s.id = f.sector_id
 AND s.organizacion_id = p.organizacion_id
LEFT JOIN LATERAL (
  SELECT r.*
  FROM public.intervenciones_rag r
  WHERE r.vencimiento_id = v.id
  ORDER BY r.aplicado_at DESC, r.created_at DESC
  LIMIT 1
) rag ON true
LEFT JOIN LATERAL (
  SELECT o.*
  FROM public.vencimiento_observaciones o
  WHERE o.vencimiento_id = v.id
    AND rag.id IS NOT NULL
    AND o.observada_at > rag.aplicado_at
  ORDER BY o.observada_at DESC, o.id DESC
  LIMIT 1
) obs ON true
WHERE v.activo = true;

REVOKE ALL ON TABLE public.v_seguimiento_rag_actual FROM PUBLIC, anon;
GRANT SELECT ON TABLE public.v_seguimiento_rag_actual TO authenticated;

COMMENT ON VIEW public.v_seguimiento_rag_actual IS
  'Seguimiento del RAG más reciente por vencimiento: compara reducción física del stock comprometido y VMD de Glaciar contra la velocidad requerida antes de donación.';

COMMIT;
