-- Glaciar 0258: persistencia trazable y compatible con el importador existente.
-- No redefine todavía qué campo de costo alimentará el cálculo económico.

ALTER TABLE public.importaciones
  DROP CONSTRAINT IF EXISTS importaciones_tipo_reporte_check;
ALTER TABLE public.importaciones
  ADD CONSTRAINT importaciones_tipo_reporte_check
  CHECK (tipo_reporte IN ('reposicion_asistida', 'glaciar_0258'));

ALTER TABLE public.producto_sucursal
  ADD COLUMN IF NOT EXISTS stock_transito numeric,
  ADD COLUMN IF NOT EXISTS per_ant_3 numeric,
  ADD COLUMN IF NOT EXISTS per_ant_2 numeric,
  ADD COLUMN IF NOT EXISTS per_ant_1 numeric,
  ADD COLUMN IF NOT EXISTS ultimo_periodo numeric,
  ADD COLUMN IF NOT EXISTS precio_sugerido numeric,
  ADD COLUMN IF NOT EXISTS precio_venta numeric,
  ADD COLUMN IF NOT EXISTS fecha_ultima_importacion_0258 timestamptz;

ALTER TABLE public.producto_snapshots
  ADD COLUMN IF NOT EXISTS stock_transito numeric,
  ADD COLUMN IF NOT EXISTS per_ant_3 numeric,
  ADD COLUMN IF NOT EXISTS per_ant_2 numeric,
  ADD COLUMN IF NOT EXISTS per_ant_1 numeric,
  ADD COLUMN IF NOT EXISTS ultimo_periodo numeric,
  ADD COLUMN IF NOT EXISTS costo_unitario_observado numeric,
  ADD COLUMN IF NOT EXISTS costo_final_observado numeric,
  ADD COLUMN IF NOT EXISTS precio_sugerido numeric,
  ADD COLUMN IF NOT EXISTS precio_venta numeric;

CREATE TABLE IF NOT EXISTS public.importacion_0258_detalle (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  importacion_id uuid NOT NULL REFERENCES public.importaciones(id) ON DELETE CASCADE,
  organizacion_id uuid NOT NULL REFERENCES public.organizaciones(id) ON DELETE RESTRICT,
  sucursal_id uuid NOT NULL REFERENCES public.sucursales(id) ON DELETE RESTRICT,
  producto_id uuid REFERENCES public.productos(id) ON DELETE SET NULL,
  cod_art text NOT NULL,
  descripcion text,
  marca text,
  contenido text,
  unidad_medida text,
  bulto numeric,
  dto_sec_fam text,
  costo_unitario numeric,
  costo_final numeric,
  precio_sugerido numeric,
  precio_venta numeric,
  stock_transito numeric,
  stock numeric,
  per_ant_3 numeric,
  per_ant_2 numeric,
  per_ant_1 numeric,
  ultimo_periodo numeric,
  venta_media_diaria numeric,
  fila_origen integer,
  captured_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT importacion_0258_detalle_import_cod_uk UNIQUE (importacion_id, cod_art)
);

CREATE INDEX IF NOT EXISTS importacion_0258_detalle_producto_idx
  ON public.importacion_0258_detalle (producto_id, captured_at DESC);
CREATE INDEX IF NOT EXISTS importacion_0258_detalle_org_cod_idx
  ON public.importacion_0258_detalle (organizacion_id, cod_art, captured_at DESC);

CREATE TABLE IF NOT EXISTS public.producto_costo_observaciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizacion_id uuid NOT NULL REFERENCES public.organizaciones(id) ON DELETE RESTRICT,
  producto_id uuid NOT NULL REFERENCES public.productos(id) ON DELETE CASCADE,
  sucursal_fuente_id uuid NOT NULL REFERENCES public.sucursales(id) ON DELETE RESTRICT,
  importacion_id uuid NOT NULL REFERENCES public.importaciones(id) ON DELETE CASCADE,
  costo_unitario numeric,
  costo_final numeric,
  observado_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT producto_costo_observaciones_import_producto_uk UNIQUE (importacion_id, producto_id),
  CONSTRAINT producto_costo_observaciones_alguno_check CHECK (costo_unitario IS NOT NULL OR costo_final IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS producto_costo_observaciones_producto_idx
  ON public.producto_costo_observaciones (organizacion_id, producto_id, observado_at DESC);

CREATE TABLE IF NOT EXISTS public.producto_costo_ultima_observacion (
  producto_id uuid PRIMARY KEY REFERENCES public.productos(id) ON DELETE CASCADE,
  organizacion_id uuid NOT NULL REFERENCES public.organizaciones(id) ON DELETE RESTRICT,
  sucursal_fuente_id uuid NOT NULL REFERENCES public.sucursales(id) ON DELETE RESTRICT,
  importacion_id uuid NOT NULL REFERENCES public.importaciones(id) ON DELETE RESTRICT,
  costo_unitario numeric,
  costo_final numeric,
  observado_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT producto_costo_ultima_alguno_check CHECK (costo_unitario IS NOT NULL OR costo_final IS NOT NULL)
);

ALTER TABLE public.importacion_0258_detalle ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.producto_costo_observaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.producto_costo_ultima_observacion ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.importacion_0258_detalle FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.producto_costo_observaciones FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.producto_costo_ultima_observacion FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION noven_private.persistir_detalle_0258_v1(
  p_importacion_id uuid,
  p_sucursal_id uuid,
  p_items jsonb
) RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE
  v_org_id uuid;
  v_aplicada_at timestamptz;
BEGIN
  IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' THEN
    RAISE EXCEPTION 'p_items debe ser un array JSON';
  END IF;

  SELECT i.organizacion_id, COALESCE(i.aplicada_at, now())
    INTO v_org_id, v_aplicada_at
  FROM public.importaciones i
  WHERE i.id = p_importacion_id
    AND i.sucursal_id = p_sucursal_id;

  IF v_org_id IS NULL THEN
    RAISE EXCEPTION 'Importación 0258 inexistente o fuera de la sucursal';
  END IF;

  INSERT INTO public.importacion_0258_detalle (
    importacion_id, organizacion_id, sucursal_id, producto_id,
    cod_art, descripcion, marca, contenido, unidad_medida, bulto, dto_sec_fam,
    costo_unitario, costo_final, precio_sugerido, precio_venta,
    stock_transito, stock, per_ant_3, per_ant_2, per_ant_1, ultimo_periodo,
    venta_media_diaria, fila_origen, captured_at
  )
  SELECT
    p_importacion_id,
    v_org_id,
    p_sucursal_id,
    p.id,
    btrim(x.cod_art),
    NULLIF(btrim(x.descripcion), ''),
    NULLIF(btrim(x.marca), ''),
    NULLIF(btrim(x.contenido), ''),
    NULLIF(btrim(x.unidad_medida), ''),
    x.bulto,
    NULLIF(btrim(x.dto_sec_fam), ''),
    x.costo_unitario,
    x.costo_final,
    x.precio_sugerido,
    x.precio_venta,
    x.stock_transito,
    x.stock,
    x.per_ant_3,
    x.per_ant_2,
    x.per_ant_1,
    x.ultimo_periodo,
    x.venta_media_diaria,
    x.fila_origen,
    v_aplicada_at
  FROM jsonb_to_recordset(p_items) AS x(
    cod_art text,
    descripcion text,
    marca text,
    contenido text,
    unidad_medida text,
    bulto numeric,
    dto_sec_fam text,
    costo_unitario numeric,
    costo_final numeric,
    precio_sugerido numeric,
    precio_venta numeric,
    stock_transito numeric,
    stock numeric,
    per_ant_3 numeric,
    per_ant_2 numeric,
    per_ant_1 numeric,
    ultimo_periodo numeric,
    venta_media_diaria numeric,
    fila_origen integer
  ) x
  LEFT JOIN public.productos p
    ON p.organizacion_id = v_org_id
   AND p.cod_art = btrim(x.cod_art)
   AND p.activo = true
  ON CONFLICT (importacion_id, cod_art) DO UPDATE SET
    producto_id = EXCLUDED.producto_id,
    descripcion = EXCLUDED.descripcion,
    marca = EXCLUDED.marca,
    contenido = EXCLUDED.contenido,
    unidad_medida = EXCLUDED.unidad_medida,
    bulto = EXCLUDED.bulto,
    dto_sec_fam = EXCLUDED.dto_sec_fam,
    costo_unitario = EXCLUDED.costo_unitario,
    costo_final = EXCLUDED.costo_final,
    precio_sugerido = EXCLUDED.precio_sugerido,
    precio_venta = EXCLUDED.precio_venta,
    stock_transito = EXCLUDED.stock_transito,
    stock = EXCLUDED.stock,
    per_ant_3 = EXCLUDED.per_ant_3,
    per_ant_2 = EXCLUDED.per_ant_2,
    per_ant_1 = EXCLUDED.per_ant_1,
    ultimo_periodo = EXCLUDED.ultimo_periodo,
    venta_media_diaria = EXCLUDED.venta_media_diaria,
    fila_origen = EXCLUDED.fila_origen,
    captured_at = EXCLUDED.captured_at;

  -- Sólo enriquecemos estado/snapshot para filas que el importador principal
  -- realmente aplicó. Los SKU pendientes conservan el detalle crudo sin inventar estado.
  UPDATE public.producto_snapshots ps
  SET stock_transito = d.stock_transito,
      per_ant_3 = d.per_ant_3,
      per_ant_2 = d.per_ant_2,
      per_ant_1 = d.per_ant_1,
      ultimo_periodo = d.ultimo_periodo,
      costo_unitario_observado = d.costo_unitario,
      costo_final_observado = d.costo_final,
      precio_sugerido = d.precio_sugerido,
      precio_venta = d.precio_venta
  FROM public.importacion_0258_detalle d
  WHERE ps.importacion_id = p_importacion_id
    AND d.importacion_id = p_importacion_id
    AND d.producto_id = ps.producto_id;

  UPDATE public.producto_sucursal psu
  SET stock_transito = d.stock_transito,
      per_ant_3 = d.per_ant_3,
      per_ant_2 = d.per_ant_2,
      per_ant_1 = d.per_ant_1,
      ultimo_periodo = d.ultimo_periodo,
      precio_sugerido = d.precio_sugerido,
      precio_venta = d.precio_venta,
      fecha_ultima_importacion_0258 = v_aplicada_at,
      updated_at = now()
  FROM public.importacion_0258_detalle d
  WHERE d.importacion_id = p_importacion_id
    AND d.producto_id = psu.producto_id
    AND psu.sucursal_id = p_sucursal_id
    AND EXISTS (
      SELECT 1
      FROM public.producto_snapshots snap
      WHERE snap.importacion_id = p_importacion_id
        AND snap.producto_id = d.producto_id
    );

  INSERT INTO public.producto_costo_observaciones (
    organizacion_id, producto_id, sucursal_fuente_id, importacion_id,
    costo_unitario, costo_final, observado_at
  )
  SELECT DISTINCT
    v_org_id, d.producto_id, p_sucursal_id, p_importacion_id,
    d.costo_unitario, d.costo_final, v_aplicada_at
  FROM public.importacion_0258_detalle d
  WHERE d.importacion_id = p_importacion_id
    AND d.producto_id IS NOT NULL
    AND (d.costo_unitario IS NOT NULL OR d.costo_final IS NOT NULL)
    AND EXISTS (
      SELECT 1
      FROM public.producto_snapshots snap
      WHERE snap.importacion_id = p_importacion_id
        AND snap.producto_id = d.producto_id
    )
  ON CONFLICT (importacion_id, producto_id) DO UPDATE SET
    costo_unitario = EXCLUDED.costo_unitario,
    costo_final = EXCLUDED.costo_final,
    observado_at = EXCLUDED.observado_at;

  INSERT INTO public.producto_costo_ultima_observacion (
    producto_id, organizacion_id, sucursal_fuente_id, importacion_id,
    costo_unitario, costo_final, observado_at, updated_at
  )
  SELECT
    o.producto_id, o.organizacion_id, o.sucursal_fuente_id, o.importacion_id,
    o.costo_unitario, o.costo_final, o.observado_at, now()
  FROM public.producto_costo_observaciones o
  WHERE o.importacion_id = p_importacion_id
  ON CONFLICT (producto_id) DO UPDATE SET
    organizacion_id = EXCLUDED.organizacion_id,
    sucursal_fuente_id = EXCLUDED.sucursal_fuente_id,
    importacion_id = EXCLUDED.importacion_id,
    costo_unitario = EXCLUDED.costo_unitario,
    costo_final = EXCLUDED.costo_final,
    observado_at = EXCLUDED.observado_at,
    updated_at = now()
  WHERE EXCLUDED.observado_at >= public.producto_costo_ultima_observacion.observado_at;
END;
$function$;

REVOKE ALL ON FUNCTION noven_private.persistir_detalle_0258_v1(uuid, uuid, jsonb) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.aplicar_importacion_0258_familia_v1(
  p_sucursal_id uuid,
  p_usuario_id uuid,
  p_codigo_sucursal_fuente text,
  p_codigo_familia text,
  p_nombre_archivo text,
  p_archivo_sha256 text,
  p_filas_total integer,
  p_filas_validas integer,
  p_filas_descartadas integer,
  p_operaciones jsonb,
  p_detalle_items jsonb,
  p_fecha_reporte date DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE
  v_result jsonb;
  v_importacion_id uuid;
  v_existente record;
BEGIN
  IF NOT public.validar_operacion_local_server_v1(p_usuario_id, p_sucursal_id) THEN
    RAISE EXCEPTION 'El usuario no tiene permiso operativo para importar esta familia en la sucursal'
      USING ERRCODE = '42501';
  END IF;

  SELECT i.id, i.estado INTO v_existente
  FROM public.importaciones i
  WHERE i.sucursal_id = p_sucursal_id
    AND i.tipo_reporte = 'glaciar_0258'
    AND i.archivo_sha256 = p_archivo_sha256;

  IF v_existente.id IS NOT NULL THEN
    RETURN jsonb_build_object('duplicada', true, 'importacion_id', v_existente.id, 'estado', v_existente.estado, 'fuente', 'glaciar_0258');
  END IF;

  v_result := public.aplicar_importacion_glaciar_familia_v1(
    p_sucursal_id, p_usuario_id, p_codigo_sucursal_fuente, p_codigo_familia,
    p_nombre_archivo, p_archivo_sha256, p_filas_total, p_filas_validas,
    p_filas_descartadas, p_operaciones, p_fecha_reporte
  );

  IF COALESCE((v_result->>'duplicada')::boolean, false) THEN
    RETURN v_result;
  END IF;

  v_importacion_id := (v_result->>'importacion_id')::uuid;
  UPDATE public.importaciones
  SET tipo_reporte = 'glaciar_0258'
  WHERE id = v_importacion_id;

  PERFORM noven_private.persistir_detalle_0258_v1(v_importacion_id, p_sucursal_id, p_detalle_items);
  RETURN v_result || jsonb_build_object('fuente', 'glaciar_0258');
END;
$function$;

CREATE OR REPLACE FUNCTION public.aplicar_importacion_0258_masiva_v1(
  p_sucursal_id uuid,
  p_usuario_id uuid,
  p_codigo_sucursal_fuente text,
  p_nombre_archivo text,
  p_archivo_sha256 text,
  p_filas_total integer,
  p_filas_validas integer,
  p_filas_descartadas integer,
  p_items jsonb,
  p_detalle_items jsonb,
  p_fecha_reporte date DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE
  v_result jsonb;
  v_importacion_id uuid;
  v_existente record;
BEGIN
  IF NOT public.validar_operacion_local_server_v1(p_usuario_id, p_sucursal_id) THEN
    RAISE EXCEPTION 'El usuario no tiene permiso operativo para importar en la sucursal'
      USING ERRCODE = '42501';
  END IF;

  SELECT i.id, i.estado INTO v_existente
  FROM public.importaciones i
  WHERE i.sucursal_id = p_sucursal_id
    AND i.tipo_reporte = 'glaciar_0258'
    AND i.archivo_sha256 = p_archivo_sha256;

  IF v_existente.id IS NOT NULL THEN
    RETURN jsonb_build_object('duplicada', true, 'importacion_id', v_existente.id, 'estado', v_existente.estado, 'fuente', 'glaciar_0258');
  END IF;

  v_result := public.aplicar_importacion_glaciar_masiva_v2(
    p_sucursal_id, p_usuario_id, p_codigo_sucursal_fuente, p_nombre_archivo,
    p_archivo_sha256, p_filas_total, p_filas_validas, p_filas_descartadas,
    p_items, p_fecha_reporte
  );

  IF COALESCE((v_result->>'duplicada')::boolean, false) THEN
    RETURN v_result;
  END IF;

  v_importacion_id := (v_result->>'importacion_id')::uuid;
  UPDATE public.importaciones
  SET tipo_reporte = 'glaciar_0258'
  WHERE id = v_importacion_id;

  PERFORM noven_private.persistir_detalle_0258_v1(v_importacion_id, p_sucursal_id, p_detalle_items);
  RETURN v_result || jsonb_build_object('fuente', 'glaciar_0258');
END;
$function$;

REVOKE ALL ON FUNCTION public.aplicar_importacion_0258_familia_v1(uuid, uuid, text, text, text, text, integer, integer, integer, jsonb, jsonb, date) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.aplicar_importacion_0258_masiva_v1(uuid, uuid, text, text, text, integer, integer, integer, jsonb, jsonb, date) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.aplicar_importacion_0258_familia_v1(uuid, uuid, text, text, text, text, integer, integer, integer, jsonb, jsonb, date) TO service_role;
GRANT EXECUTE ON FUNCTION public.aplicar_importacion_0258_masiva_v1(uuid, uuid, text, text, text, integer, integer, integer, jsonb, jsonb, date) TO service_role;
