-- DESAFIO 5S
-- Migración aditiva: no modifica tablas existentes de Noven.

create table if not exists public.desafio5s_participantes (
  id bigint generated by default as identity primary key,
  legajo text not null,
  nombre text not null,
  apellido text not null,
  sector text not null check (sector in ('Gerencia','Administración','Línea de cajas','Salón','Carnicería','Verdulería','Maestranza','Lácteos','Panadería')),
  es_prueba_admin boolean not null default false,
  puntaje integer not null default 0,
  respuestas_correctas integer not null default 0,
  total_preguntas integer not null default 15,
  completado_at timestamptz not null default now()
);

-- Un colaborador puede tener una sola participación oficial.
-- Las pruebas administrativas quedan excluidas de esta restricción.
create unique index if not exists desafio5s_un_oficial_por_legajo
  on public.desafio5s_participantes (legajo)
  where es_prueba_admin = false;

create index if not exists desafio5s_ranking_idx
  on public.desafio5s_participantes (puntaje desc, completado_at asc)
  where es_prueba_admin = false;

alter table public.desafio5s_participantes enable row level security;

-- No se agregan políticas permisivas en esta migración.
-- El acceso se habilitará expresamente según el flujo de autenticación elegido,
-- evitando abrir datos o tablas productivas de Noven accidentalmente.
