-- =============================================================================
-- MULTITENANT V1 · FASE 3A — historial de importaciones y snapshots
--
-- Objetivo:
--   Cada CSV deja de ser solamente una actualización del estado actual y pasa a
--   convertirse en evidencia histórica inmutable por sucursal.
--
-- Seguridad:
--   Estas tablas nacen SERVER-ONLY. `authenticated` no recibe privilegios
--   directos todavía. Las futuras pantallas consumirán vistas/RPC con scope RLS
--   explícito. Esto reduce la superficie de exposición durante la transición.
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 1. IMPORTACIONES — cabecera/auditoría de cada archivo procesado
-- -----------------------------------------------------------------------------
CREATE TABLE public.importaciones (
  id                       uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organizacion_id          uuid        NOT NULL REFERENCES public.organizaciones(id) ON DELETE RESTRICT,
  sucursal_id              uuid        NOT NULL,
  usuario_id               uuid        REFERENCES public.usuarios(id) ON DELETE SET NULL,
  tipo_reporte             text        NOT NULL CHECK (tipo_reporte IN ('reposicion_asistida')),
  codigo_sucursal_fuente   text        NOT NULL,
  fecha_reporte            date,
  nombre_archivo           text        NOT NULL,
  archivo_sha256           text        NOT NULL CHECK (archivo_sha256 ~ '^[0-9a-f]{64}$'),
  filas_total              integer     NOT NULL DEFAULT 0 CHECK (filas_total >= 0),
  filas_validas            integer     NOT NULL DEFAULT 0 CHECK (filas_validas >= 0),
  filas_descartadas        integer     NOT NULL DEFAULT 0 CHECK (filas_descartadas >= 0),
  estado                   text        NOT NULL DEFAULT 'recibida'
                             CHECK (estado IN ('recibida', 'validada', 'aplicada', 'fallida', 'cancelada')),
  error_detalle            text,
  created_at               timestamptz NOT NULL DEFAULT now(),
  aplicada_at              timestamptz,

  CONSTRAINT importaciones_sucursal_org_fk
    FOREIGN KEY (sucursal_id, organizacion_id)
    REFERENCES public.sucursales(id, organizacion_id)
    ON DELETE RESTRICT,

  -- El mismo archivo físico no puede aplicarse dos veces a la misma sucursal y
  -- tipo de reporte. El SHA-256 se calcula sobre los bytes originales.
  CONSTRAINT importaciones_archivo_unico
    UNIQUE (sucursal_id, tipo_reporte, archivo_sha256),

  CONSTRAINT importaciones_estado_aplicada_check CHECK (
    estado <> 'aplicada' OR aplicada_at IS NOT NULL
  )
);

CREATE INDEX importaciones_sucursal_fecha_idx
  ON public.importaciones(sucursal_id, created_at DESC);
CREATE INDEX importaciones_org_fecha_idx
  ON public.importaciones(organizacion_id, created_at DESC);
CREATE INDEX importaciones_usuario_idx
  ON public.importaciones(usuario_id)
  WHERE usuario_id IS NOT NULL;

ALTER TABLE public.importaciones ENABLE ROW LEVEL SECURITY;

-- Rechazar explícitamente acceso browser mientras el flujo nuevo no esté
-- cableado. service_role conserva capacidad server-side y bypass de RLS.
REVOKE ALL ON TABLE public.importaciones FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.importaciones TO service_role;

COMMENT ON TABLE public.importaciones IS
  'Auditoría inmutable por archivo importado: sucursal fuente, hash, usuario, estado y conteos.';

-- -----------------------------------------------------------------------------
-- 2. PRODUCTO_SNAPSHOTS — fotografía SKU × sucursal por importación
--
-- No se aplican CHECK stock>=0 ni VMD>=0. El snapshot es evidencia del sistema
-- fuente y debe conservar incluso valores anómalos (por ejemplo stock teórico
-- negativo por diferencias de inventario). La capa analítica los clasificará;
-- el histórico no debe silenciarlos ni hacer fallar el archivo entero.
-- -----------------------------------------------------------------------------
CREATE TABLE public.producto_snapshots (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  importacion_id      uuid        NOT NULL REFERENCES public.importaciones(id) ON DELETE RESTRICT,
  organizacion_id     uuid        NOT NULL REFERENCES public.organizaciones(id) ON DELETE RESTRICT,
  sucursal_id         uuid        NOT NULL,
  producto_id         uuid        NOT NULL,
  stock               integer     NOT NULL,
  venta_media_diaria  numeric     NOT NULL DEFAULT 0,
  fila_origen         integer,
  captured_at         timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT producto_snapshots_sucursal_org_fk
    FOREIGN KEY (sucursal_id, organizacion_id)
    REFERENCES public.sucursales(id, organizacion_id)
    ON DELETE RESTRICT,

  CONSTRAINT producto_snapshots_producto_org_fk
    FOREIGN KEY (producto_id, organizacion_id)
    REFERENCES public.productos(id, organizacion_id)
    ON DELETE RESTRICT,

  CONSTRAINT producto_snapshots_import_producto_uk
    UNIQUE (importacion_id, producto_id),

  CONSTRAINT producto_snapshots_fila_check CHECK (fila_origen IS NULL OR fila_origen > 0)
);

CREATE INDEX producto_snapshots_sucursal_producto_fecha_idx
  ON public.producto_snapshots(sucursal_id, producto_id, captured_at DESC);
CREATE INDEX producto_snapshots_org_fecha_idx
  ON public.producto_snapshots(organizacion_id, captured_at DESC);
CREATE INDEX producto_snapshots_importacion_idx
  ON public.producto_snapshots(importacion_id);

ALTER TABLE public.producto_snapshots ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.producto_snapshots FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.producto_snapshots TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.producto_snapshots_id_seq TO service_role;

COMMENT ON TABLE public.producto_snapshots IS
  'Serie histórica fiel del sistema fuente: stock y venta media por SKU/sucursal, incluyendo valores anómalos.';

-- -----------------------------------------------------------------------------
-- 3. Consistencia cruzada importación ↔ snapshot
--
-- Las FK individuales prueban que producto y sucursal pertenecen a la misma
-- organización, pero además un snapshot debe pertenecer a la MISMA sucursal y
-- organización que su cabecera de importación.
-- -----------------------------------------------------------------------------
ALTER TABLE public.importaciones
  ADD CONSTRAINT importaciones_id_org_sucursal_uk
  UNIQUE (id, organizacion_id, sucursal_id);

ALTER TABLE public.producto_snapshots
  ADD CONSTRAINT producto_snapshots_import_scope_fk
  FOREIGN KEY (importacion_id, organizacion_id, sucursal_id)
  REFERENCES public.importaciones(id, organizacion_id, sucursal_id)
  ON DELETE RESTRICT;

COMMIT;
